# NAME THE PIPELINE SAME AS FILE (WITHOUT ".yml")

resources:
  repositories:
    - repository: self
      trigger: none

variables:
  azureServiceConnection: 'a78ee3d8-7299-436d-b245-dafcde1f1f52'
  subscriptionId: '5e445ad6-3cbb-4c06-b4aa-4429e91115d2'
  resourceGroup: 'VisualStudioOnline-3343EDD561274EF3A0D8E1195506A72D'
  location: 'northeurope'

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: Deploy ACR using Bicep
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: $(azureServiceConnection)
        subscriptionId: $(subscriptionId)
        action: 'Create Or Update Resource Group'
        resourceGroupName: '$(resourceGroup)'
        location: '$(location)'
        templateLocation: 'Linked artifact'
        csmFile: 'infra/acr.bicep'
        deploymentMode: 'Incremental'
        deploymentOutputs: 'outputJson'
    - task: PowerShell@2
      displayName: Parse Bicep Output
      inputs:
        targetType: 'inline'
        script: |
          $var=ConvertFrom-Json '$(outputJson)'
          $value=$var.acrLoginServer.value
          Write-Host "##vso[task.setvariable variable=acrLoginServer;]$value"
    - task: Docker@0
      displayName: 'Build the docker image'
      inputs:
        azureSubscription: $(azureServiceConnection)
        azureContainerRegistry: $(acrLoginServer)
        dockerFile: 'src/Web/Dockerfile'
        defaultContext: false
        context: $(Build.SourcesDirectory)
        includeLatestTag: true
        imageName: eshoponweb/web:$(Build.BuildId)
    - task: Docker@0
      displayName: 'Push the docker images'
      inputs:
        azureSubscription: $(azureServiceConnection)
        azureContainerRegistry: $(acrLoginServer)
        action: 'Push an image'
        imageName: eshoponweb/web:$(Build.BuildId)
        includeLatestTag: true
    
